name: Déploiement sur l'espace demo

on:
  push:
    branches: [main]
env:
  branch:
jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Retrieve cached dependencies
        id: retrieve-dependencies
        uses: actions/cache@v2
        with:
          key: node_modules-${{ hashFiles('yarn.lock') }}
          path: node_modules
      - name: Install dependencies
        if: steps.retrieve-dependencies.outputs.cache-hit == false
        run: yarn --frozen-lockfile
      - name: Cache dependencies if not present
        if: steps.retrieve-dependencies.outputs.cache-hit == false
        uses: actions/cache@v2
        with:
          key: node_modules.-${{ hashFiles('yarn.lock') }}
          path: node_modules

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Override .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_STRATEGYAUTH: "local"
          envkey_REACT_APP_VERSION: "1.0"
          envkey_REACT_APP_API: ${{ secrets.REACT_APP_API_DEMO }}
          envkey_REACT_APP_CV_FILE_MAX_SIZE: 10485760
          file_name: .env
      - name: Build application
        run: yarn run build
      - name: copy .htaccess
        uses: canastro/copy-file-action@master
        with:
          source: ".htaccess"
          target: "build/.htaccess"
      - name: Upload release bundle as artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: /

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve bundle React
        uses: actions/download-artifact@v2
        with:
          name: bundle
      - name: Deploy on clever cloud
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: ${{ secrets.CLEVER_CLOUD_GIT_PORTAIL_CANDIDAT_DEMOTESTSEB }}
          BRANCH: master
          FOLDER: build
          SSH_PRIVATE_KEY: ${{ secrets.CLEVER_CLOUD_DEPLOY_PRIVATE_KEY }}
          KNOWN_HOSTS_FILE: resources/known_hosts
